# Generated by Django 4.1.7 on 2023-03-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='light_mode',
        ),
        migrations.AddField(
            model_name='profile',
            name='access_code',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
