# Generated by Django 4.1.7 on 2023-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0002_remove_profile_light_mode_profile_access_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
