# Generated by Django 4.1.7 on 2023-03-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0003_alter_profile_github_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
