# Generated by Django 4.1.7 on 2023-03-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0005_remove_profile_access_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitissue',
            name='lamports',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitissue',
            name='github_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gitrepository',
            name='github_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
