# Generated by Django 4.1.7 on 2023-03-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0006_gitissue_lamports_alter_gitissue_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitissue',
            name='minimum_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
