# Generated by Django 4.1.7 on 2023-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0009_gitissue_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitissue',
            name='pda',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
