# Generated by Django 4.1.7 on 2023-03-13 22:14

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0011_gitwebhook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gitwebhook',
            name='github_id',
        ),
        migrations.RemoveField(
            model_name='gitwebhook',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='gitwebhook',
            name='lamports',
        ),
        migrations.RemoveField(
            model_name='gitwebhook',
            name='minimum_date',
        ),
        migrations.RemoveField(
            model_name='gitwebhook',
            name='pda',
        ),
        migrations.RemoveField(
            model_name='gitwebhook',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='gitwebhook',
            name='user',
        ),
        migrations.AddField(
            model_name='gitwebhook',
            name='data',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
