# Generated by Django 4.1.7 on 2023-03-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0012_remove_gitwebhook_github_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitwebhook',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
