# Generated by Django 4.1.7 on 2023-03-14 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Connect', '0014_bountypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gitissue',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gitissue',
            name='branch_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='gitissue',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
